# Generated by Django 5.1.5 on 2025-10-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='geoserver_nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
